baseURL = "https://www.zahnarztpraxis-bielefeld.de/"
locale = "de-DE"
title = "Zahnarztpraxis Bielefeld"

[params]
  logoIcon = "🦷"

[params.social]
  facebook = "https://www.facebook.com/zahnarztpraxis.bielefeld"
  instagram = "#"
